""" from https://github.com/keithito/tacotron """

"""
Defines the set of symbols used in text input to the model.
"""
# _pad = "_"
# _punctuation = ';:,.!?¡¿—…"«»“” '
# _letters = "nhtcgiuamđàovưrlábykpsôạếdóảêệấờộớốâìềểợơủqxịậầữíựúăắeứọụãởồặùòừổũỏửẽỉéẹẩýẫằẻễỗĩỡỹèẳõỳỷẵỵ"
# _letters_ipa = "atːəɜ26ni̪ŋhɪy4omɲɗɡɔkɛuzʊvel5bɕʂʃwxfpsjcɣ1()æɹdɒɑʌʒ7ðɐʐ"

pad = "_"
punctuation = ["!", "?", "…", ",", ".", "'", "-"]
pu_symbols = punctuation + ["SP", "UNK"]
normal_symbols = [
           'ɯəj', 
           'ɤ̆j', 
           'ʷiə', 
           'ɤ̆w', 
           'ɯəw', 
           'ʷet', 
           'iəw', 
           'uəj', 
           'ʷen', 
           'tʰw', 
           'ʷɤ̆', 
           'ʷiu', 
           'kwi', 
           'ŋ͡m', 
           'k͡p', 
           'cw', 
           'jw', 
           'uə', 
           'eə', 
           'bw', 
           'oj', 
           'ʷi', 
           'vw', 
           'ăw', 
           'ʈw', 
           'ʂw', 
           'aʊ', 
           'fw', 
           'ɛu', 
           'tʰ', 
           'tʃ', 
           'ɔɪ', 
           'xw', 
           'ʷɤ', 
           'ɤ̆', 
           'ŋw', 
           'ʊə', 
           'zi', 
           'ʷă', 
           'dw', 
           'eɪ', 
           'aɪ', 
           'ew', 
           'iə', 
           'ɣw', 
           'zw', 
           'ɯj', 
           'ʷɛ', 
           'ɯw', 
           'ɤj', 
           'ɔ:', 
           'əʊ', 
           'ʷa', 
           'mw', 
           'ɑ:', 
           'hw', 
           'ɔj', 
           'uj', 
           'lw', 
           'ɪə', 
           'ăj', 
           'u:', 
           'aw', 
           'ɛj', 
           'iw', 
           'aj', 
           'ɜ:', 
           'kw', 
           'nw', 
           't∫', 
           'ɲw', 
           'eo', 
           'sw', 
           'tw', 
           'ʐw', 
           'iɛ', 
           'ʷe', 
           'i:', 
           'ɯə', 
           'dʒ', 
           'ɲ', 
           'θ', 
           'ʌ', 
           'l', 
           'w', 
           'ɪ', 
           'ɯ', 
           'd', 
           '∫', 
           'p', 
           'ə', 
           'u', 
           'o', 
           'ɣ', 
           '!', 
           'ð', 
           'ʧ', 
           'ʒ', 
           'ʐ', 
           'z', 
           'v', 
           'g', 
           'ă', 
           'æ', 
           'ɤ', 
           'ʤ', 
           'i', 
           '.', 
           'ɒ', 
           'b', 
           'h', 
           'n', 
           'ʂ', 
           'ɔ', 
           'ɛ', 
           'k', 
           'm', 
           ' ', 
           'c', 
           'j', 
           'x', 
           'ʈ', 
           ',', 
           'ʊ', 
           's', 
           'ŋ', 
           'a', 
           'ʃ', 
           '?', 
           'r', 
           ':', 
           'η', 
           'f', 
           ';', 
           'e', 
           't', 
           "'"]
num_tones = 7

# Export all symbols:
symbols = [pad] + sorted(set(normal_symbols + pu_symbols))

# Special symbol ids
SPACE_ID = symbols.index(" ")
